name: GitHub Actions DotNet
on: 
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  Job-DotNet-Push:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 7.0.x
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      DOTNET_NOLOGO: true
      BUILD_CONFIGURATION: Release
      PROJECT_PATH: 'WebApplicationIntcomex/WebApplicationIntcomex'
      PROJECT_TEST_PATH: 'UnitTest/**.UnitTest'
    steps:
      - name: Check out repository code ('${{ github.repository }}' cloned to the runner)
        uses: actions/checkout@v2
    
      
